  spring:
    config:
      import: optional:configserver:http://localhost:8888
    application:
      name: Document-server
    mail:
      host: smtp.gmail.com
      port: 587
      username: faresfelhi2@gmail.com
      password: allxuqotoqzlyqbh

      servlet:
        multipart:
          enabled: true

      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
