spring:
  datasource:
    url: jdbc:mysql://localhost:3306/INTERVIEW?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hedilatrache19201920@gmail.com
    password: 27238522
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8084

eureka:
   client:
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:8761/eureka
