spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sae71?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto:create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8070

application:
  config:
    user-service-url: http://localhost:8222/api/v1/users
