spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: convention-service

  spring:
    web:
      cors:
        allowed-origins: "http://localhost:4200"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true

